### ISSUE TITLE
is-core-module polyfill broke Workbox and Jest?

### ISSUE THREAD

**Issue by wojtekmaj** [SukkaW/nolyfill#77]
(still investigating; to be updated 

After recent nolyfill update in a couple of repos, I've seen quite a lot of CI failures. I'm going to investigate more when I'm not on mobile, but clues so far: 

Vite+Workbox build:

```
Error: Dynamic require of "workbox-build" is not supported
    at file:///home/runner/work/app/app/.yarn/__virtual__/vite-plugin-pwa-virtual-d6945bcd64/0/cache/vite-plugin-pwa-npm-0.20.0-a60c090b45-6bffcfedd7.zip/node_modules/vite-plugin-pwa/dist/chunk-UB6OAFZF.js:6:9
    at loadWorkboxBuild (file:///home/runner/work/app/app/.yarn/__virtual__/vite-plugin-pwa-virtual-d6945bcd64/0/cache/vite-plugin-pwa-npm-0.20.0-a60c090b45-6bffcfedd7.zip/node_modules/vite-plugin-pwa/dist/index.js:300:12)
    at async generateServiceWorker (file:///home/runner/work/app/app/.yarn/__virtual__/vite-plugin-pwa-virtual-d6945bcd64/0/cache/vite-plugin-pwa-npm-0.20.0-a60c090b45-6bffcfedd7.zip/node_modules/vite-plugin-pwa/dist/index.js:345:26)
    at async _generateSW (file:///home/runner/work/app/app/.yarn/__virtual__/vite-plugin-pwa-virtual-d6945bcd64/0/cache/vite-plugin-pwa-npm-0.20.0-a60c090b45-6bffcfedd7.zip/node_modules/vite-plugin-pwa/dist/index.js:480:5)
    at async Object.handler (file:///home/runner/work/app/app/.yarn/__virtual__/vite-plugin-pwa-virtual-d6945bcd64/0/cache/vite-plugin-pwa-npm-0.20.0-a60c090b45-6bffcfedd7.zip/node_modules/vite-plugin-pwa/dist/index.js:638:13)
    at async PluginDriver.hookParallel (file:///home/runner/work/app/app/.yarn/cache/rollup-npm-4.13.0-6c6a010f12-90f8cdf9c2.zip/node_modules/rollup/dist/es/shared/node-entry.js:19485:17)
    at async Object.close (file:///home/runner/work/app/app/.yarn/cache/rollup-npm-4.13.0-6c6a010f12-90f8cdf9c2.zip/node_modules/rollup/dist/es/shared/node-entry.js:20418:13)
    at async build (file:///home/runner/work/app/app/.yarn/__virtual__/vite-virtual-d0e74f95a7/0/cache/vite-npm-5.3.1-0fe9027262-9317262c02.zip/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65687:17)
    at async CAC.<anonymous> (file:///home/runner/work/app/app/.yarn/__virtual__/vite-virtual-d0e74f95a7/0/cache/vite-npm-5.3.1-0fe9027262-9317262c02.zip/node_modules/vite/dist/node/cli.js:828:5)
```

Jest:
```
● Validation Error:

  Preset react-native not found.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

Process completed with exit code 1.
```

**Comment by SukkaW** [comment]
#78 might be related?
